[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aioboto3>=15.5.0",
    "boto3>=1.40.61",
    "fastapi>=0.136.3",
    "openai>=2.38.0",
    "python-dotenv>=1.2.2",
    "redis>=7.4.0",
    "sse-starlette>=3.4.4",
    "tavily-python>=0.7.24",
    "uvicorn>=0.48.0",
]
